name: Film Listesi Guncelle

on:
  schedule:
    # Her gün Türkiye saatiyle sabah 06:00'da otomatik çalışır
    - cron: '0 3 * * *'
  workflow_dispatch: # İstediğinde elle başlatabilmen için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: |
          pip install requests

      - name: Filmleri Cek
        run: python film_cekici.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add FilmDizi.m3u
          git commit -m "Film listesi guncellendi: $(date)" || echo "Degisiklik yok"
          git push
